---
- hosts: localhost
  vars:
    hostname: pynet-rtr1  
  tasks:
    - name: Generate configuration file
      template: src=../template/access_switch.j2 dest=/home/jfisher/testpy/configs/{{item.hostname}}.txt
      with_items:
            - {hostname: pynet-rtr1, access_vlan: 10,  ip_addr: 10.1.1.2, default_gateway: 10.1.1.1, snmp_community: public, secret: password, acl: True}
            - {hostname: pynet-rtr2, access_vlan: 20,  ip_addr: 10.1.2.2, default_gateway: 10.1.2.1, snmp_community: public, secret: password, acl: False}
            - {hostname: pynet-rtr3, access_vlan: 30,  ip_addr: 10.1.3.2, default_gateway: 10.1.3.1, snmp_community: public, secret: password, acl: True}
            - {hostname: pynet-rtr4, access_vlan: 40,  ip_addr: 10.1.4.2, default_gateway: 10.1.4.1, snmp_community: public, secret: password, acl: True}
            - {hostname: pynet-rtr5, access_vlan: 50,  ip_addr: 10.1.5.2, default_gateway: 10.1.5.1, snmp_community: public, secret: password, acl: False}
