---

- name: Arista Exercise 1
  hosts: arista

  tasks:
    - name: Set interface ethernet 6 description
      eos_interface: name=Ethernet6 description=""
            username={{eapi_username}}
            password={{eapi_password}}
            host={{eapi_hostname}}
            port={{eapi_port}}
            transport=https
    
    - name: Set interface ethernet 6 back to access vlan 1
      eos_switchport: name=Ethernet6 mode=access access_vlan=1
            username={{eapi_username}}
            password={{eapi_password}}
            host={{eapi_hostname}}
            port={{eapi_port}}
            transport=https 

    - name: Removes vlan from exercise 1
      eos_vlan: vlanid={{item.vlan_id}} name={{item.vlan_name}} state=absent
            username={{eapi_username}}
            password={{eapi_password}}
            host={{eapi_hostname}}
            port={{eapi_port}}
            transport=https
      with_items:
        - {vlan_name: red, vlan_id: 110}
        - {vlan_name: blue, vlan_id: 111}
        - {vlan_name: green, vlan_id: 112}
