---

- name: Cisco File Transfer
  hosts: cisco

  tasks:
    - name: Transfer file to cisco rtr
      cisco_file_transfer:
            source_file=/home/jfisher/ANSIBLE/cisco_logging.txt
            dest_file=cisco_logging.txt
            overwrite=true
            enable_scp=true
            host={{host}}
            password={{password}}
            port={{port}}
            username={{username}}
